name: DEV

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'workflow/*'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checando o código
      uses: actions/checkout@v3

    
    - name: Verificando tipo de arquivos (exemplo para .ipynb)
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.ipynb$'; then
          echo "Arquivos Jupyter Notebook modificados!"
        else
          echo "Nenhum arquivo Jupyter Notebook modificado!"
        fi

    - name: Validando estilo de código (exemplo para Jupyter Notebook usando flake8)
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.ipynb$'; then
          pip install flake8
          flake8 .
        fi

  Valida-nome-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Verifique o evento e extraia o nome da branch corretamente
      run: |
        # Verifique o evento e extraia o nome da branch corretamente
        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          BRANCH_NAME="${GITHUB_REF##*/}"  # Para push, extrai a branch diretamente
        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          BRANCH_NAME="${GITHUB_HEAD_REF}"  # Para PR, usa GITHUB_HEAD_REF
        else
          echo "Erro: Evento não suportado"
          exit 1
        fi
        
        echo "BRANCH_NAME: $BRANCH_NAME"  # Exibe o nome da branch para depuração
        
        # Verifica se a branch segue os padrões permitidos (feature/*, bugfix/*, workflow/*)
        if [[ "$BRANCH_NAME" =~ ^feature/.* || "$BRANCH_NAME" =~ ^bugfix/.* || "$BRANCH_NAME" =~ ^workflow/.* ]]; then
          echo "A branch $BRANCH_NAME é uma branch válida."
        else
          echo "Erro: A branch não segue um padrão permitido (feature/*, bugfix/*, workflow/*)."
          exit 1
        fi
      shell: bash