name: DEV

on:
  push:
    branches:
      - 'feature/*'  # Esse workflow será acionado quando um push for feito para uma branch de feature.
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checando o código
      uses: actions/checkout@v3  # Faz o checkout do código do repositório

    
    - name: Verificando tipo de arquivos (exemplo para .ipynb)
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.ipynb$'; then
          echo "Arquivos Jupyter Notebook modificados!"
        else
          echo "Nenhum arquivo Jupyter Notebook modificado!"
        fi

    - name: Validando estilo de código (exemplo para Jupyter Notebook usando flake8)
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.ipynb$'; then
          pip install flake8
          flake8 .
        fi

  validate-and-create-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Validar nome da branch
      run: |
        # Extrair o nome da branch dependendo do evento
        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          BRANCH_NAME="${GITHUB_REF##*/}"  # Para push, extrai a branch diretamente
        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          BRANCH_NAME="${GITHUB_HEAD_REF}"  # Para PR, usa GITHUB_HEAD_REF
        else
          echo "Erro: Evento não suportado"
          exit 1
        fi

        # Verifica se a branch segue o padrão feature/*
        if [[ ! "$BRANCH_NAME" =~ ^feature/ ]]; then
          echo "Erro: A branch não é uma branch de feature (feature/*)."
          exit 1
        fi
        echo "A branch $BRANCH_NAME é uma branch de feature."

    - name: Criar PR para a branch develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Criando PR da branch $BRANCH_NAME para develop..."
        curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d '{"title":"Automated PR from feature branch to develop","head":"'$BRANCH_NAME'","base":"develop"}' \
        https://api.github.com/repos/${{ github.repository }}/pulls

    - name: Criar PR para a branch main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Criando PR da branch $BRANCH_NAME para main..."
        curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d '{"title":"Automated PR from feature branch to main","head":"'$BRANCH_NAME'","base":"main"}' \
        https://api.github.com/repos/${{ github.repository }}/pulls
