name: Validar Branch e Criar PRs

on:
  push:
    branches:
      - 'feature/*'  # Esse workflow será acionado quando um push for feito para uma branch de feature.

jobs:
  validate-and-create-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Validar nome da branch
      run: |
        BRANCH_NAME="${GITHUB_REF##*/}"  # Extrai o nome da branch
        if [[ ! "$BRANCH_NAME" =~ ^feature/ ]]; then
          echo "Erro: A branch não é uma branch de feature (feature/*)."
          exit 1
        fi
        echo "A branch $BRANCH_NAME é uma branch de feature."

    - name: Criar PR para a branch develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="${GITHUB_REF##*/}"
        echo "Criando PR da branch $BRANCH_NAME para develop..."
        curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d '{"title":"Automated PR from feature branch to develop","head":"'$BRANCH_NAME'","base":"develop"}' \
        https://api.github.com/repos/${{ github.repository }}/pulls

    - name: Criar PR para a branch main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="${GITHUB_REF##*/}"
        echo "Criando PR da branch $BRANCH_NAME para main..."
        curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d '{"title":"Automated PR from feature branch to main","head":"'$BRANCH_NAME'","base":"main"}' \
        https://api.github.com/repos/${{ github.repository }}/pulls
